httpPort: 6660
domainName:
  - http://localhost:6660
  - http://localhost:5173
token: maruko
log:
  cmd: info
  file: all
redis:
  host: localhost
  port: 6379
  password: null
email:
  host: smtp.qq.com
  port: 587
  secure: false
  auth:
    user: # 请填写您的邮箱
    pass: # 请填写您的邮箱密码
  from: MarukoNode <请填写您的邮箱地址>
